# Generated by Django 4.2 on 2024-01-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_booking_comment_remove_booking_guest_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='inventory',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
